version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
      - "dependencies"
      - "javascript"
    groups:
      # Try to group everything that uses Babel together to avoid
      # ending up with stray outdated transitive Babel dependencies
      # that need to be manually updated.
      #
      # Patterns generated based on the output of:
      #
      #     pnpm why --json '@babel/*' | jq '[.[].devDependencies | keys[]]'
      dev-babel-dependents:
        dependency-type: "development"
        patterns:
          - "@babel/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "jest"
          - "@types/jest"
          - "postcss-loader"
          - "stylelint*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
      - "dependencies"
      - "ruby"
