version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   labels:
  #     - "automerge"
  #     - "dependencies"
  #     - "javascript"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
      - "dependencies"
      - "ruby"
