os: linux
dist: bionic
language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
      - tree
  firefox: latest
branches:
  except:
    # Master is the actually deployed code
    - master
env:
  global:
    - ORIG_PATH: $PATH
    - BUNDLE_PATH: ~/.bundle
    - GH_REF: github.com/wabain/wabain.github.io.git
    - USER_INSTALL_DIR: ~/bin
    - PATH: $USER_INSTALL_DIR:~/.yarn/bin:$PATH
    - secure: iaR8CNeimqE/vQhZf/WAZu5D2qZCBkF+j3HcGM5ZSPzLgZXz1UH0y/xVyYYqalIDNUburYQBrEbl/qRcUeD7foew4Kd4XbwiOdmoqOIPPiO2fwKq/EcCWxDpAiQRlSv7gocGOG6EOgnxQaE+K3PYXcDUcklKElIvYNYCq7g5ZXI1/yudkllOiffnmEZzdBcxOdkrLgNlPacML8q8P1ATrzk80AWeoE830rB9OIiOB0jXbfS1Iz8yELWNSdv0jRe6yYooUv+VM1nkCiorChr9GKRI2Y8I7TuoeKJ/XKbb5s9/ptSABVgWxVXFIcSfm1iwYs7/JNdcHftGpUQMCgZuEDsiah6BELBCbB+lVJHvodoxw/JuSBVcOFSQebvYTpYNi21bjAjKZr0ue4wf1iTxNonGEnbE7/fp87AXwzU/CaBXSlb/WwKWNXIN0n7iGu5tT+HU0c+VA+U9h3ulfBsY+1/3p2Ypj3suJgsPQ5R7S1LDBUNwA+LBOy/Q/ebQTl8PDhUXrByVneHFxWVzHW9dxfygIXsBCM7k3S53IedaAqbAUPy3RWeWMdOhGyv4pI/5/KExnTfh4INJUHUK9NKroSz8fw8GkBL1jZE9AmTgaXq28YxBaRhTyaqvE10kmg26OBi+gW7riItexmldZdj9j86zDrajh6ao/LfIMtkt4jI=
cache:
  yarn: true
  directories:
    - node_modules
    - $BUNDLE_PATH
before_install:
  - ./bin/ci-install-geckodriver.sh
  # When populating the cache, Travis may update the path to include
  # node_modules/.bin; if present, node-which will break RVM's check for curl
  - RUBY_VERSION="$(bin/ruby-version.sh)" && ( PATH=$ORIG_PATH rvm install "$RUBY_VERSION" ) && rvm use "$RUBY_VERSION"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
install:
  - bundle install
  - yarn install
before_script:
  - git config --global user.email "bain.william.a+ci@gmail.com"
  - git config --global user.name "Travis CI"
script:
  - yarn run lint-build-infra
  - JEKYLL_ENV=production yarn run pre-jekyll
  - JEKYLL_ENV=production yarn run jekyll-build
  - JEKYLL_ENV=production yarn run jekyll-lint
  - ./bin/ci-run-integration-tests.sh
  - ./bin/ci-deploy.sh
