plugins:
  - jekyll-redirect-from
incremental:
  true
source: content
defaults:
  -
    scope:
      path: ""
    values:
      assets_dir: "/home-assets"
      layout: "page"
  -
    scope:
      path: "section-partial"
    values:
      layout: "section-partial"
