plugins:
  - jekyll-redirect-from
incremental:
  true
exclude:
  - node_modules
  - Gruntfile.js
  - Vagrantfile
  - Gemfile*
  - package.json
  - yarn.lock
  - "*.sh"
  - "*.sublime-*"
defaults:
  -
    scope:
      path: ""
    values:
      assets_dir: "/home-assets"
      layout: "page"
  -
    scope:
      path: "section-partial"
    values:
      layout: "section-partial"
