plugins:
  - jekyll-redirect-from
# builds are fast enough that there's no need for the occasional
# soundness issues that incremental builds create
incremental: false
include:
  - .site-meta.json
defaults:
  -
    scope:
      path: ""
    values:
      assets_dir: "/home-assets"
      layout: "page"
      longform: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      longform: true
  -
    scope:
      path: "section-partial"
    values:
      layout: "section-partial"
  -
    scope:
      path: "section-partial/2018"
    values:
      layout: "post-partial"
      longform: true
  -
    scope:
      path: "section-partial/2019"
    values:
      layout: "post-partial"
      longform: true
  -
    scope:
      path: "section-partial/2020"
    values:
      layout: "post-partial"
      longform: true
