plugins:
  - jekyll-redirect-from
incremental:
  true
include:
  - .site-meta.json
defaults:
  -
    scope:
      path: ""
    values:
      assets_dir: "/home-assets"
      layout: "page"
      partial_layout: "section-partial"
