plugins:
  - jekyll-redirect-from
  - jekyll-archives
# builds are fast enough that there's no need for the occasional
# soundness issues that incremental builds create
incremental: false
include:
  - .site-meta.json
defaults:
  - scope:
      path: ""
    values:
      assets_dir: "/home-assets"
      layout: "page"
      partial_layout: "section-partial"
      longform: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      partial_layout: "post-partial"
      longform: true
  - scope:
      path: "tag"
    values:
      partial_layout: "tag-partial"
      longform: true
jekyll-archives:
  enabled: [tags]
  layout: tag
  permalinks:
    tag: '/tag/:name/'
