plugins:
  - jekyll-redirect-from
incremental:
  true
defaults:
  - scope:
      path: ""
    values:
      assets_dir: "/home-assets"
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
  - scope:
      path: "section-partial"
    values:
      layout: "section-partial"
