name: Install common dependencies
inputs:
  dependencies:
    description: Which dependencies to install
    required: true
    default: |
      tree
      jq
      pnpm
      poetry
      geckodriver
      sentry-cli
      unzip

  github-token:
    description: Token to authenticate with when requesting geckodriver artifacts
    required: false

env:
  # Use a default rcfile. See the comment in .github/workflows/validate.yml
  BASH_ENV: ci/env.sh

runs:
  using: composite
  steps:
    - name: Validate inputs
      id: validated
      shell: bash -e {0}
      env:
        INPUT_DEPENDENCIES: ${{ inputs.dependencies }}
      run: |
        set -euo pipefail

        jq --null-input --raw-output '
          env.INPUT_DEPENDENCIES |
            split("\n") |
            [
              .[] |
              # Strip whitespace
              gsub("^\\s+|\\s+$"; "") |
              # Filter empty entries
              select(. != "") |
              if test("^(tree|jq|pnpm|poetry|geckodriver|sentry-cli|unzip)$") then
                .
              else
                error("::error ::Unknown dependency: \(.)")
              end
            ] |
            "dependencies=\(. | tojson)"
        ' |
        tee -a "$GITHUB_OUTPUT"

    - name: Create user install dir
      shell: bash -e {0}
      run: mkdir -p $USER_INSTALL_DIR

    - name: Install apt dependencies
      shell: bash -e {0}
      env:
        DEPS: ${{ steps.validated.outputs.dependencies }}
      run: |
        apt_deps="$(jq --null-input --raw-output '
          [env.DEPS | fromjson[] | select(test("^(tree|unzip)$"))] | join(" ")
        ')"

        [[ ! -z "$apt_deps" ]] || exit 0

        echo "::group::Install apt dependencies ($apt_deps)"
        sudo apt-get update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install $apt_deps
        echo "::endgroup::"

    - name: Install pnpm
      shell: bash -e {0}
      env:
        NEEDED: ${{ contains(fromJSON(steps.validated.outputs.dependencies), 'pnpm') }}
        VERSION: "8.6.2"
      run: |
        [[ "$NEEDED" == true ]] || exit 0

        echo "::group::Install pnpm"
        npm install --global "pnpm@$VERSION"
        echo "::endgroup::"

    - name: Install poetry
      shell: bash -e {0}
      env:
        NEEDED: ${{ contains(fromJSON(steps.validated.outputs.dependencies), 'poetry') }}
        VERSION: "1.8.2"
      run: |
        [[ "$NEEDED" == true ]] || exit 0

        echo "::group::Install poetry"
        pipx install "poetry==$VERSION"
        echo "::endgroup::"

    - name: Install jq
      shell: bash -e {0}
      env:
        NEEDED: ${{ contains(fromJSON(steps.validated.outputs.dependencies), 'jq') }}
      run: |
        [[ "$NEEDED" == true ]] || exit 0

        echo "::group::Install jq"
        bin/ci-install-jq.sh
        echo "::endgroup::"

    - name: Install geckodriver
      shell: bash -e {0}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        NEEDED: ${{ contains(fromJSON(steps.validated.outputs.dependencies), 'geckodriver') }}
      run: |
        [[ "$NEEDED" == true ]] || exit 0

        if [ -z "$GH_TOKEN" ]; then
          echo '::error ::github-token input is required to install geckodriver'
          exit 1
        fi

        echo "::group::Install geckodriver"
        bin/ci-install-geckodriver.sh
        echo "::endgroup::"

    - name: Install sentry-cli
      shell: bash -e {0}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        NEEDED: ${{ contains(fromJSON(steps.validated.outputs.dependencies), 'sentry-cli') }}
      run: |
        [[ "$NEEDED" == true ]] || exit 0

        if [ -z "$GH_TOKEN" ]; then
          echo '::error ::github-token input is required to install sentry-cli'
          exit 1
        fi

        echo "::group::Install sentry-cli"
        bin/ci-install-sentry-cli.sh
        echo "::endgroup::"

    - name: List dependency executable versions
      shell: bash -e {0}
      run: |
        print-version() {
          local cmd=$1
          shift

          local args="$@"
          if [ -z "$args" ]; then
            args=--version
          fi

          if ! hash "$cmd" &> /dev/null; then
            echo "$cmd: not installed"
            return
          fi

          echo "$cmd ($(which "$cmd")): $("$cmd" $args 2>&1 | head -n1)"
        }

        echo 'Dependencies (externally managed):'
        print-version ruby
        print-version bundler
        print-version python
        print-version pipx

        echo
        echo 'Dependencies (via install-system-deps):'
        print-version firefox
        print-version geckodriver
        print-version git
        print-version jq
        print-version node
        print-version tree
        print-version sentry-cli
        print-version unzip -v
        print-version pnpm
        print-version poetry
