name: Check deploy after push to develop
run-name: Check deploy eligibility after run ${{ github.event.workflow_run.html_url }}
on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]

jobs:
  # When triggered by push to develop branch
  check-post-push-deploy:
    name: Check deploy eligibility for develop build

    # Assert there is a single pull request associated with the payload—I think that should be
    # the case for the pull_request event type
    if: >
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'develop'

    uses: ./.github/workflows/merge-deploy.yml
    secrets: inherit

    with:
      workflow_run_id: ${{ github.event.workflow_run.id }}
      effective_event: push
      head_ref: ${{ github.event.workflow_run.head_branch }}
      base_ref: ${{ github.event.workflow_run.head_branch }}
      push_commit: ${{ github.event.workflow_run.head_sha }}
