name: Deploy if eligible
run-name: Deploy ${{ inputs.ref }} (${{ inputs.push_commit }})
on:
  workflow_call:
    inputs:
      workflow_run_id:
        description: "The ID of the workflow run whose output should be deployed"
        type: number
        required: true

      ref:
        description: "The branch to deploy from"
        required: true
        type: string

      push_commit:
        description: "The SHA of the commit to deploy from"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "The ID of the workflow run whose output should be deployed"
        type: number
        required: true

      ref:
        description: "The branch to deploy from"
        required: true
        type: string

      push_commit:
        description: "The SHA of the commit to deploy from"
        required: true
        type: string

jobs:
  check-merge-deploy:
    name: Deploy using artifact
    runs-on: ubuntu-22.04

    env:
      # See comment in validate.yml
      BASH_ENV: ci/env.sh

    steps:
      - name: Validate inputs
        env:
          ref: ${{ inputs.ref }}
          TARGET_REF: develop
        run: |
          set -euo pipefail

          if [[ "$ref" != "$TARGET_REF" ]]; then
            echo "::error ::Can only deploy directly from $TARGET_REF (got $ref);" \
              "use merge-queue to deploy other branches"
            exit 1
          fi

      - name: Configure git
        run: |
          git config --global user.email "bain.william.a+ci@gmail.com"
          git config --global user.name "CI"

      - uses: actions/checkout@v6

      - name: Install system dependencies
        uses: ./.github/actions/install-system-deps
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dependencies: |
            jq
            sentry-cli

      # Keep download and extract steps in sync with merge-queue.yml
      - name: Download build
        uses: actions/download-artifact@v7
        with:
          name: site.tgz
          path: ${{ runner.temp }}/build
          run-id: ${{ inputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract build
        env:
          BUILD_DIR: ${{ runner.temp }}/build
        run: |
          set -euo pipefail

          if [[ ! -f "$BUILD_DIR/site.revisions.json" ]]; then
            echo "::error ::missing site.revisions.json in build artifact"
            exit 1
          fi

          tar -xzf "$BUILD_DIR/site.tgz" -C "$BUILD_DIR" site

      - name: Push eligible refs
        id: push-refs
        env:
          CI_DRY_RUN: "false"
          BUILD_DIR: ${{ runner.temp }}/build
          REF: ${{ inputs.ref }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          set -euo pipefail

          args=()

          [[ "$CI_DRY_RUN" != false ]] && args+=( --dry-run )

          bin/ci-tools deploy-commit \
            "${args[@]}" \
            --ref "$REF" \
            --deploy-dir "$BUILD_DIR/site" \
            --deploy-revision-info "$BUILD_DIR/site.revisions.json" \
            --run-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
            --outputs-file "$GITHUB_OUTPUT"
