name: Check for mergeable PRs needing action
on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_call:
  workflow_dispatch:

jobs:
  poll-mergeable:
    runs-on: ubuntu-22.04

    env:
      # See comment in validate.yml
      BASH_ENV: ci/env.sh

    steps:
      - uses: actions/checkout@v3

      - name: Evaluate if pull request automerge required
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token with repo access and without the builtin GITHUB_TOKEN restrictions
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          bin/ci-trigger-next-pr.sh
