name: Pull request updated
on:
  pull_request:
    types: [labeled]

  pull_request_review: {}

jobs:
  eval-automerge:
    runs-on: ubuntu-18.04

    env:
      # See comment in base.yml
      BASH_ENV: ci/env.sh

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        uses: ./.github/actions/install-system-deps
        with:
          dependencies: jq

      - name: Evaluate if pull request automerge required
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token with repo access
          GH_WRITE_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
        run: |
          bin/ci-trigger-pr-rerun.sh
